name: Docker Push
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Login to Docker Hub'
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: 'Build Docker Image'
        run: |
          docker buildx create --name builder --use \
            --tag ${{ secrets.DOCKER_USERNAME }}/vesky-bot:$(echo ${GITHUB_REF:10}) \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
      - name: 'Push version tagged Docker Image'
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/vesky-bot:$(echo ${GITHUB_REF:10})
      - name: 'Retag Docker Image'
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/vesky-bot:$(echo ${GITHUB_REF:10}) ${{ secrets.DOCKER_USERNAME }}/vesky-bot:latest
      - name: 'Push latest Docker Image'
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/vesky-bot:latest
