name: Docker Push
on:
  push:
    tags:
      - 'v*'
jobs:
  push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Login to Docker Hub'
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: 'Build Docker Image'
        run: |
          docker build . -t ${{ secrets.DOCKER_USERNAME }}/vesky-bot:${{ github.ref }}
      - name: 'Push Docker Image'
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/vesky-bot:$(echo ${GITHUB_REF:10})
