name: Docker Push
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Login to Docker Hub'
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: 'Set repo name environment variable'
        env:
          REPO_NAME: ${{ secrets.DOCKER_USERNAME }}/vesky-bot
          REPO_VERSION: $(echo ${GITHUB_REF:10})
      - name: 'Build Docker Image'
        run: |
          docker build . -t $REPO_NAME:$REPO_VERSION
      - name: 'Tag Docker Image'
        run: |
          docker tag $REPO_NAME:$REPO_VERSION $REPO_NAME:latest
      - name: 'Push Docker Image'
        run: |
          docker push $REPO_NAME:latest
