name: Docker Push
on:
  push:
    branches:
      - deploy
jobs:
  push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Login to Docker Hub'
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin ${{ secrets.DOCKER_PASSWORD }}
      - name: 'Build Docker Image'
        run: |
          docker build . -t ${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}:1.0
      - name: 'Push Docker Image'
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}:1.0
