name: Docker Push
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Login to Docker Hub'
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: 'Install arm64 Emulator'
        run: |
          docker run --privileged --rm tonistiigi/binfmt --install arm64
      - name: 'Create Builder'
        run: |
          docker buildx create --name builder --use
      - name: 'Build and Push Docker Image'
        run: |
          docker buildx build \
            --tag ${{ secrets.DOCKER_USERNAME }}/vesky-bot:$(echo ${GITHUB_REF:10}) \
            --push \
            --platform linux/amd64,linux/arm64 .
